name: "webeasy"
services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      default:
        ipv4_address: 172.0.0.2

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - postgresql

  app:
    image: kore:myself
    working_dir: /webeasy
    networks:
      - default
    ports:
      - 8888:8888
    volumes:
      - ./:/webeasy
    command: kore -c conf/app.conf
    depends_on:
      - postgresql

networks:
  default:
    ipam:
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
