version: "3.8"
name: "webeasy"
services:

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    networks:
      default:
        ipv4_address: 172.0.0.2

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - default
    depends_on:
      - postgresql

  app:
    image: kore/kore:git-master-arm64
    working_dir: /app
    environment:
      PG_IPADDR: 172.0.0.2
    networks:
      - default
    ports:
      - 8888:8888
    volumes:
      - ${PWD}/app:/app
    command: -c conf/app.conf
    depends_on:
      - postgresql

networks:
  default:
    ipam:
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1
